CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "."

# Model Constants
IGNORE_INDEX = -100
IMAGE_TOKEN_INDEX = -200
POINTCLOUD_TOKEN_INDEX = -300
DEFAULT_IMAGE_TOKEN = "<image>"
DEFAULT_IMAGE_PATCH_TOKEN = "<im_patch>"
DEFAULT_IM_START_TOKEN = "<im_start>"
DEFAULT_IM_END_TOKEN = "<im_end>"
IMAGE_PLACEHOLDER = "<image-placeholder>"
DEFAULT_POINTCLOUD_TOKEN = "<pointcloud>"
DEFAULT_PC_START_TOKEN = "<pc_start>"
DEFAULT_PC_END_TOKEN = "<pc_end>"
POINTCLOUD_PLACEHOLDER = "<pointcloud-placeholder>"
